### PR TITLE
Upgrades: fix keyword arguments across versions

### LINKED ISSUE #28: Callable: Introduction of double splat breaks keyword parameters
**What**
The [recent introduction](https://github.com/thread-pond/junk_drawer/pull/26) of the double splat (`**`) operator to `Callable` has caused `call` methods with default parameter values to break.

**Steps to reproduce**
Add the following test to `callable_spec`:
```ruby
it 'works when there is a default parameter' do
  class MyCallableClass
    include JunkDrawer::Callable
    def call(who = 'World')
      "Hello, #{who}!"
    end
  end

  expected = "Hello, World!"
  expect(MyCallableClass.()).to eq expected
end
```
The following error is received:
```ruby
  1) JunkDrawer::Callable works when there is a default parameter
     Failure/Error: expect(MyCallableClass.()).to eq expected
     
       expected: "Hello, World!"
            got: "Hello, {}!"
     
       (compared using ==)
     # ./spec/junk_drawer/callable_spec.rb:20:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by mockdeep**
Fixes #28. Ruby 2.6 splat arguments behave differently from Ruby 2.7
splat arguments which behave (slightly) differently from Ruby 3.0 splat
arguments. It turns out it's hard to handle all of them gracefully, but
thankfully a little gem called [`ruby2_keywords`][rbkw] is provided by
Ruby core for us to transition smoothly. For Ruby versions 2.6 and
earlier, it is a no-op. For Ruby versions 2.7 and up, the method is
already defined in core Ruby, in which cases the gem does nothing. The
core version internally translates the arguments to Ruby 3 style keyword
arguments. You can read all about the complexities [here][blog]. There
are several other suggested ways of handling the issue, but this seemed
to be the cleanest. Once Ruby <= 2.6 support is dropped, this should be
able to be removed.

[rbkw]: https://github.com/ruby/ruby2_keywords
[blog]: https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html

### CODE REVIEW

File: spec/junk_drawer/callable_spec.rb [hunk 1]
```diff
@@ -20,6 +20,18 @@ def call(one_arg, who:)
...
+    class MyCallableClass
+      include JunkDrawer::Callable
+      def call(one_arg = 'foo')
+        "calling in, #{one_arg}"
+      end
+    end
+
+    expected = 'calling in, foo'
+    expect(MyCallableClass.()).to eq expected
+  end
```
Comment (raychatter) [inline spec/junk_drawer/callable_spec.rb:33]: 🎉 🎉 🎉 
image

**Review by raychatter — APPROVED** [review]
Good find!
